name: MultiJobWorkflow

on:
  workflow_dispatch:

jobs:
  FirstJob:
    runs-on: ubuntu-latest

    steps:
      - name: Linux Commands
        run: |
          echo "I am the first job-updated"
          
  SecondJob:
    runs-on: ubuntu-latest
    needs: FirstJob
    
    steps:
      - name: Linux Commands
        run: |
          echo "I am the Second job"

  ThirdJob:
    runs-on: ubuntu-latest
    needs: [FirstJob, SecondJob]
    
    steps:
      - name: Linux Commands
        run: |
          echo "I am the Second job"
